version: '3'
services:

  youTubedatapipeline:
    build: .
    image: youtube-data-pipeline:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
